### ISSUE TITLE
Type mismatch for Datepicker props with TS: onChange vs value

### ISSUE THREAD

**Issue by NoahMLoomis** [onesine/react-tailwindcss-datepicker#1]
Awesome tool, just what I was looking for.

There seems to be a type mismatch. The `value` prop has the following type:

```
 value: {
        startDate: Date | string,
        endDate: Date | string,
    } | null
```
But the value passed in the `onChange` is the following:
```
value: {
        startDate: string | null,
        endDate: string | null
     }
```

So when trying to change the value you get the following error:
![image](https://user-images.githubusercontent.com/56049624/204024622-2f9f1d01-5984-4311-b337-5a9692d26a5d.png)
I'll create a PR for this

**Comment by NoahMLoomis** [comment]
PR here: https://github.com/onesine/react-tailwindcss-datepicker/pull/2

**Comment by onesine** [comment]
Hi @NoahMLoomis  👋.
You are indeed right. I didn't pay attention to that at all. Thank you for the remark and especially for making a PR to correct it.

I am happy to accept your contribution to the project.

I thank you very much and I hope you will be there for other features as the package is young.

**Comment by onesine** [comment]
@NoahMLoomis 
I noticed in your PR you had made these changes. 
```
value: {
    startDate: string | Date,
    endDate: string | Date
} | null,

onChange: (value: {startDate: string | Date, endDate: string | Date} | null) => void
```
But the values of startDate and endDate should be able to be null. An example would be when you delete the form.

Then it should be
```
value: {
    startDate: string | Date | null,
    endDate: string | Date | null
} | null,

onChange: (value: {startDate: string | Date | null, endDate: string | Date | null} | null) => void
```

**Comment by onesine** [comment]
But I took this into account in the patch for version 1.1.1

**Comment by NoahMLoomis** [comment]
Awesome! Good catch
