### ISSUE TITLE
Datepicker triggers the form to submit

### ISSUE THREAD

**Issue by JefteCaro** [onesine/react-tailwindcss-datepicker#10]
Thank you for this great project. Loved it!

Just ran into some minor issues when the Datepicker is used inside a form.

Any click within the calendar submits the form.

PR here #9

**Comment by onesine** [comment]
Hi 👋 @JefteCaro 

Thank you very much for this feedback, I hadn't thought about that at all.

Thank you also for the PR and it will be a pleasure to have you contribute even more on this project with me.

**Comment by onesine** [comment]
I really appreciate your PR @JefteCaro . It will be a pleasure to work with you on this project.

Currently I do not have a way to test the datepicker directly from the project. Do you have any suggestions for me.

**Comment by JefteCaro** [comment]
Thank you @onesine!

I'd love you contribute more on this project of yours.

How about having [jest](https://jestjs.io)?

**Comment by JefteCaro** [comment]
Closing thread.
Fixed in #9

**Comment by onesine** [comment]
Yes I've heard of jest before. But I was talking about a way to test the component live from a browser.

**Comment by JefteCaro** [comment]
How about [cypress](https://docs.cypress.io).
You might like this one.

**Comment by onesine** [comment]
Thanks @JefteCaro  for the suggestion. I'll try it and see.
