### ISSUE TITLE
Is it possible to add additional shortcuts?

### ISSUE THREAD

**Issue by anil-resero** [onesine/react-tailwindcss-datepicker#106]
Looks like the current mechanism only allows `last 7 days` and `last 30 days` using the `past` shortcut attribute. I am looking to add `last 90 days`, and `last 180 days` etc.

**Comment by onesine** [comment]
Hi @anil-resero 👋

Thank you for your feedback.

This feature is planned for a new version. So it will be available soon.

**Comment by onesine** [comment]
Hi @anil-resero  👋 

Sorry for the delay. 

I just added this feature. I will publish it in a new version soon.
