### ISSUE TITLE
Custom Shortcuts not working

### ISSUE THREAD

**Issue by lchluk002** [onesine/react-tailwindcss-datepicker#108]
The new Custom Shortcuts feature does not seem to be working.

I used the following `configs` setup (taken from this repo):
```js
configs={{
      shortcuts: {
          last3Days: {
              text: "Last 3 days",
              period: {
                  start: new Date(new Date().setDate(new Date().getDate() - 3)),
                  end: new Date()
              }
          },
      }
  }}
``` 

Installed packages:
"dayjs": "^1.11.7",
"react": "^18.2.0",
"react-tailwindcss-datepicker": "^1.5.1",
"tailwindcss": "^3.2.7"

**Comment by onesine** [comment]
Hi @lchluk002 👋

It's normal to have this problem. This feature is well implemented but we haven't published it on npm yet.

I will publish it by the end of the day. There are some fixes that need to be added to the new version.

**Comment by lchluk002** [comment]
Okay great. Thanks very much.
