### ISSUE TITLE
Problems after updating to version 1.6.0

### ISSUE THREAD

**Issue by reynierhdez** [onesine/react-tailwindcss-datepicker#111]
I updated to version 1.6.0. When refreshing the screen, an error is appearing (Error: Hydration failed because the initial UI does not match what was rendered on the server.), and the component layout is broken.

![image](https://user-images.githubusercontent.com/5115491/231798996-15fe0254-4d2b-45fa-9f6f-921c8a6144be.png)

![image](https://user-images.githubusercontent.com/5115491/231800083-d5bb108f-ed73-49bd-b0ac-f4b2e536093f.png)

**Comment by onesine** [comment]
Hi @reynierhdez 👋 

Thanks for the feedback.

I did the documentation update with version 1.6.0 like you and I don't have the same problem. Can you show me your code or tell me how I can reproduce this problem.

**Comment by onesine** [comment]
I still can't reproduce the error. Can you reproduce it in a codeandbox and send the link

**Comment by reynierhdez** [comment]
Now it's working.

When customizing the component, I set containerClassName to "py-0 my-0". I added "relative w-full text-gray-700" and it's working again.

Thanks

**Comment by onesine** [comment]
OK thank you for closing this issue.
