### ISSUE TITLE
Types issue with 1.6.0

### ISSUE THREAD

**Issue by AbhinavRobinson** [onesine/react-tailwindcss-datepicker#113]
Hi, while updating to 1.6.0, I found couple of type issues.

1. It might be worth using popoverDirection: "up" | "down" instead of enums.

Why?

![Screenshot 2023-04-14 at 2 00 55 PM](https://user-images.githubusercontent.com/32090909/231989647-c24aac11-8c94-42ca-92c2-394b7c1d999e.jpg)

2. Use | instead of & in Configs['shortcuts']

```ts
shortcuts?: {
        today?: string;
        yesterday?: string;
        past?: (period: number) => string;
        currentMonth?: string;
        pastMonth?: string;
    } | { // <----- change here
        [key: string]: ShortcutsItem;
    };
```

This avoids type override, ie, typescript will not combine types today into string.

Why?

![Screenshot 2023-04-14 at 2 00 34 PM](https://user-images.githubusercontent.com/32090909/231989554-610a4099-3f90-47d8-8d2e-e6e0b1b4a852.jpg)

I will submit a PR shortly.

**Comment by AbhinavRobinson** [comment]
Created #114 for this, but (2) is not fixed due to type conflict in shortcuts code.

**Comment by onesine** [comment]
Hi @AbhinavRobinson  👋 

Thank you for your feedback. 

We will resolve this issue as soon as possible.

**Comment by AbhinavRobinson** [comment]
Updated PR #114 only for fix 1.

**Comment by t0m3k** [comment]
Fixed 2 in PR https://github.com/onesine/react-tailwindcss-datepicker/pull/133
