### ISSUE TITLE
Selecting current day gets the previous day

### ISSUE THREAD

**Issue by dakinnir** [onesine/react-tailwindcss-datepicker#117]
`<Datepicker
        showShortcuts={true}
        asSingle={true}
        minDate={new Date()} 
        value={dateValue}
        onChange={handleValueChange}
      />`

**Comment by dakinnir** [comment]
<Datepicker
        showShortcuts={true}
        asSingle={true}
        minDate={new Date()} 
        value={dateValue}
        onChange={handleValueChange}
      />``

**Comment by dakinnir** [comment]
`      <Datepicker
        showShortcuts={true}
        asSingle={true}
        minDate={new Date()} 
        value={dateValue}
        onChange={handleValueChange}
      />`

**Comment by JamDev0** [comment]
Yeah, its happening with me too. Could you fix it?

**Comment by onesine** [comment]
Hi @dakinnir & @JamDev0 👋

Thank you for your feedback.

We will correct this as soon as possible.
