### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by Romvnly-Gaming** [onesine/react-tailwindcss-datepicker#12]
![image](https://user-images.githubusercontent.com/62443489/206693732-333d3604-781f-43ce-9d12-b0547ab5b392.png) 

I don't think it's working as intended

**Comment by onesine** [comment]
Hi @Romvnly-Gaming   👋

Thank you very much for the comment. I will correct it very soon.

**Comment by Rickyc81** [comment]
It still seems non-responsive to me ... 

![photo_2023-02-01_18-58-05](https://user-images.githubusercontent.com/4402040/216124651-dff51615-7ba9-4b94-8721-5c8df6714be2.jpg)

and so in my app..

![photo_2023-02-01_18-43-51](https://user-images.githubusercontent.com/4402040/216124808-3bba3da5-d10e-47a5-bb3d-11980e863f1e.jpg)
