### ISSUE TITLE
Datepicker component is changing its position while scrolling. please give a solve

### ISSUE THREAD

**Issue by shadid06** [onesine/react-tailwindcss-datepicker#127]

**Comment by onesine** [comment]
Hi @shadid06 👋

Sorry for the delay

Thanks for the feedback.

You can use the popoverDirection props with the values "up" or "down".

You can find an example in the documentation https://react-tailwindcss-datepicker.vercel.app/props#popover-direction

**Comment by shadid06** [comment]
Date picker selection button is not sticking to its position as i scroll
Down the page.
<DatePicker/> is not fixed to its position.
