### ISSUE TITLE
Pop-up direction

### ISSUE THREAD

**Issue by M3T1N** [onesine/react-tailwindcss-datepicker#128]
It's direction is top as default. How can I change that? (Sorry for my bed england. 😭)

**Comment by onesine** [comment]
Hi @M3T1N 👋

Thanks for the feedback.

You can use the popoverDirection props with the values "up" or "down".

You can find an example in the documentation https://react-tailwindcss-datepicker.vercel.app/props#popover-direction

**Comment by M3T1N** [comment]
Thank you! Is there any way to use hours with datetimes?

**Comment by onesine** [comment]
Not yet but we are working on it. This topic is covered in another issue so this one can be closed.
