### ISSUE TITLE
Use asSingle true with footer

### ISSUE THREAD

**Issue by MaewNams** [onesine/react-tailwindcss-datepicker#140]
Is there a way to use asSingle = true with the footer? When I try to do so, after the user selects a date in the calendar, it automatically closes and updates the selected date. It behaves as if I didn't add the footer at all. However, if I set asSingle = false, it works just fine.

**Comment by Elbarae1921** [comment]
Hey there, I ran into this same issue so I tried looking into it. I've created a PR => #229

**Comment by onesine** [comment]
Hi @MaewNams and @Elbarae1921 👋.
Sorry for the late reply.
Thanks @Elbarae1921 for the contribution.
