### ISSUE TITLE
Languages support

### ISSUE THREAD

**Issue by gtonussi** [onesine/react-tailwindcss-datepicker#145]
Hi, 

Are you by any chance working on a multiple language support?

I've tried to translate the months and days of week to pt-BR, but found no option to do that on documentation.

Looking at the repo, I see that on 'src/constants/index.ts' there is a LANGUAGE variable being passed as "en" wich is the parameter of a language picker function. 

Maybe this could be user defined instead of hardcoded?

If possible and in case I qualify, let me know if I can contribute on that.

**Comment by joaoazevedoJS** [comment]
you can use i18n like:

```tsx
<DatePicker
    i18n="pt-BR"
    displayFormat="DD/MM/YYYY"
    ...
/>
 ```
  
![image](https://github.com/onesine/react-tailwindcss-datepicker/assets/59920486/bf21fabf-ac5a-40cb-abdc-1976c2e817cb)
