### ISSUE TITLE
Cannot find module "Types"

### ISSUE THREAD

**Issue by pragyaInexture** [onesine/react-tailwindcss-datepicker#157]
Hello All,
Import path for "Types" defined in "react-tailwindcss-datepicker/dist/constants/index.d.ts" is wrong .

**import { ColorKeys, Colors } from "types";** instead it should be import { ColorKeys, Colors } from **"../types**

This import is giving us issue in npm run build.

![image](https://github.com/onesine/react-tailwindcss-datepicker/assets/138481006/6ba118f0-bf05-4fd5-a35a-f21b43232ce7)

**Comment by onesine** [comment]
Thanks to @calrloco for fixing this issue.
