### ISSUE TITLE
Input value does not reset on context value reset

### ISSUE THREAD

**Issue by mkbctrl** [onesine/react-tailwindcss-datepicker#16]
I am not 100% sure it's an issue, but it looks like one to me. I am using your component with ReactHookForm via Controller:

```
<Controller
    control={control}
    name="created"
    render={({ field: { onChange, value } }) => {
      return (
        // Input text is not cleared on form reset, value is emptied properly
        <Datepicker
          value={value}
          onChange={onChange}
          useRange={false}
          primaryColor="indigo"
          placeholder={t('filters.date.placeholder.created')}
        />
      )
    }}
  />
```

and when I attempt to reset the form values, the value inside the state gets cleared, but the value of the input does not.
Is it on purpose and I am not getting smth or it's a legit bug?

Here the recording when I clear the state values:
https://user-images.githubusercontent.com/10107362/208317554-2db7671f-cfb3-4bd4-a01d-8c44d1b4e299.mov

**Comment by onesine** [comment]
Hi @mkbctrl  👋

Thanks for your feedback.

I think like you that it must be a bug. But I will try it myself to see.

**Comment by NoahMLoomis** [comment]
Hey @mkbctrl, that's an odd bug. I'm using react-hook-form as well with a controller and it works fine for me. Could be that the `useRange` prop or `placeholder` is messing something up?

```typescript
  <Controller
          control={control}
          name="availability"
          render={({ field: { onChange, value }, formState: { errors } }) => (
            <Datepicker
              value={value}
              onChange={onChange}
            />
          )}
  />
```

**Comment by mkbctrl** [comment]
Thanks for investigating the issue 🎈. Funny, it disappeared automagically
👻 at some point.

When I wanted to tackle it on my own, everything was working perfectly. I
can’t argue I don’t like the situation. For once smth is actually easy
😄😄😄

I will reopen it if I will be able to recreate it or stumble upon it again
and I will be able to understand the underlying cause. Sounds good?

**Comment by NoahMLoomis** [comment]
@onesine this issue can be closed
