### ISSUE TITLE
doesn't seem to apply styles

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [onesine/react-tailwindcss-datepicker#161]
![Screenshot 2023-07-05 at 12-08-18](https://github.com/onesine/react-tailwindcss-datepicker/assets/45887282/9d0fe23d-996d-4fdb-8146-70d52cbd8349)

**Comment by nadhilah-hizhwati** [comment]
i got the same issue please fix this :((

**Comment by calrloco** [comment]
i think u maybe forgot to add it's content to the content array in the tailwind config:
```
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.tsx',
        "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js"
    ],
}
```

**Comment by randyk69** [comment]
hello sir. i would like to thank you for creating this powerful library. it made a lot our lives easier. i'm currently experienced the same issue on my end. my tailwind config below:
`module.exports = {
    content: ["./src/**/*.{js,ts,jsx,tsx}", "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js"],
    darkMode: "class",
    theme: {},
    variants: {},
    plugins: [require("@tailwindcss/forms")]
};
`

**Comment by jshike** [comment]
> hello sir. i would like to thank you for creating this powerful library. it made our lives easier. i'm currently experiencing the same issue above on my end. my tailwind config below. `module.exports = { content: ["./src/**/*.{js,ts,jsx,tsx}", "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js"], darkMode: "class", theme: {}, variants: {}, plugins: [require("@tailwindcss/forms")] }; `
> 
> i hope and pray that you will be able to see this comment. thank you again, sir. Gbu! ps. i created a react+vite local setup and followed the instructions from your documentation when setting up the datepicker.
> 
> ![dp1](https://private-user-images.githubusercontent.com/27720505/258024836-87a53873-6427-447a-810d-bb1990e92ee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTkxMzgsIm5iZiI6MTcwNzE1ODgzOCwicGF0aCI6Ii8yNzcyMDUwNS8yNTgwMjQ4MzYtODdhNTM4NzMtNjQyNy00NDdhLTgxMGQtYmIxOTkwZTkyZWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE4NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODI3YzM3ZjVlY2MyYTAxMTBiODU4NGNhNzdjMTVhNjE2NThkYWE3NWM0OTg5OGMxOWRiMTNkN2ZkNTMxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TY6OMBVWfOmcrlb0hWQi6rZVQlwamFdHLkm8Py_iMoQ)

Still have the same issue here...
