### ISSUE TITLE
The days of the week do not match reality when there are multiple instances of the Datepicker and the i18n parameter is enabled

### ISSUE THREAD

**Issue by miquelgomis** [onesine/react-tailwindcss-datepicker#163]
I'm using the Datepicker in several places on the same page of my React application. In all of them, I have the i18n parameter enabled to customize the language. When this parameter is enabled, only the first instance works correctly; from the second instance onwards, the first day of every month always starts on a Monday, making the days of the week not match reality.
To solve this problem, I have removed the i18n parameter and am temporarily displaying the calendars in English.

The first instance works correctly:
![image](https://github.com/onesine/react-tailwindcss-datepicker/assets/3736657/ad406256-9897-47cb-9359-98594e1ff034)

From the second instance ondwards: July 1st, 2023, was a Saturday, and the 7th was actually a Friday, not a Sunday
![image](https://github.com/onesine/react-tailwindcss-datepicker/assets/3736657/b3ad5a62-6f61-4992-832a-e4ab52c82c24)

Can you give me a hand?
Thanks for your help

**Comment by bde-maze** [comment]
Hey there, I have the same issue, I would to hear if you have found anything that would fix this !

**Comment by onesine** [comment]
Hi @miquelgomis, @bde-maze 👋.
Sorry for the late reply. But I think this problem is already solved.
