### ISSUE TITLE
Calendar not showing previous month when using different dayjs.locale()

### ISSUE THREAD

**Issue by cheeselemon** [onesine/react-tailwindcss-datepicker#221]
If you declare dayjs.locale() somewhere alongside using this library,
the weekday matching function below will fail:

[react-tailwindcss-datepicker/src/helpers/index.ts](https://github.com/onesine/react-tailwindcss-datepicker/blob/bf063fe6458787622ca500ec9a33d9b2feb955d1/src/helpers/index.ts#L174)

Line 174 in [bf063fe](https://github.com/onesine/react-tailwindcss-datepicker/commit/bf063fe6458787622ca500ec9a33d9b2feb955d1)

 ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].forEach( 
because the date argument provided using getFirstDayInMonth(date).ddd
will return what was defined through dayjs.locale() other than "en" will return non english weekday string,
thus won't match anything so the variable number will always be zero.

I'm implementing a fix, and will update with a pull request.

See related: #150

**Comment by onesine** [comment]
Thanks @cheeselemon for the contribution.
