### ISSUE TITLE
[Feature Request] Should allow adding custom shortcurts in place of existing default shortcuts.

### ISSUE THREAD

**Issue by Robin-Goyal** [onesine/react-tailwindcss-datepicker#23]

**Comment by onesine** [comment]
Hello @Robin-Goyal  👋, thank you for your feedback.

Your request is part of the features we want to implement. It will be available very soon.

**Comment by yeguacelestial** [comment]
looking forward for this feature!  @onesine great work man

**Comment by onesine** [comment]
Sorry for the long wait @Robin-Goyal and @yeguacelestial. I just want to reassure you that this feature will be available soon.

PRs are always welcome 🎉.

**Comment by byanes** [comment]
Thanks @onesine! Looking forward to this feature as well! Amazing work.

**Comment by onesine** [comment]
Hi @byanes, @Robin-Goyal, @yeguacelestial 👋 

Sorry for the delay. 

I just added this feature. I will publish it in a new version soon.
