### ISSUE TITLE
[Feature Request] Disable or otherwise manipulate specific days

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [onesine/react-tailwindcss-datepicker#24]
The idea is to have a new option to disable specific days in the calendar. An application example of this could be a reservation site, where the user shouldn't be able to pick already reserved dates.

This could be implemented by adding a new option called `disabledDays` or `disabledDates`. This option could take an array where the members would be date objects or strings in `YYYY-MM-DD` format.

Optinally, the array members could be objects to provide even more customization.
Here are some I thought of:
- Background color
- Hover (render) callback (could also add a global one)
- Full control over the css of that specific date

**Comment by yoy0lol** [comment]
+1 for this.

I've been looking for a react calendar app that takes advantage of Tailwind for some time. This one came _really_ close.

It would be great where I can provide an array of days as a prop and let the component disable those specific days, or vice versa, and only allow the user to click on days that aren't disabled.

**Comment by JefteCaro** [comment]
Hi @THE-SIMPLE-MARK 

Thank you for the feedback.

See [`v1.3.4`](https://github.com/onesine/react-tailwindcss-datepicker/releases/tag/v1.3.4) 

Sample usage:

```js

const noOfficeDays = {
  new Date(), // startFrom
  new Date(), // endTo
};

const userReservedDays = {
  new Date(), // startFrom
  new Date(), // endTo
};

<Datepicker
  disabledDates={[
      noOfficeDays,
      userReservedDays,
  ]}
/>

```

Let's thank @NoahMLoomis for this feature
:clap:

**Comment by THE-SIMPLE-MARK** [comment]
Awesome, thanks so much! That is exactly what I wanted.

**Comment by Maxximus007** [comment]
@JefteCaro @NoahMLoomis Thank you for implementing disabled dates! This is really close to what I would like to use, but although the disabled dates can't be selected, it's still possible to create a range around them. 
Would it be feasible to disallow these in the range at all? In other words, stop the range at the disallowed date?

**Comment by NoahMLoomis** [comment]
@Maxximus007 Isn't this what the minDate and maxDate props are?

**Comment by Maxximus007** [comment]
@NoahMLoomis I'm using Datarange, and if I block for instance feb 11 and feb 12, I can still select a range from feb 10 until feb 13. Imho this should not be possible, since it includes the blocked dates.
![Schermafbeelding 2023-02-03 om 14 35 58](https://user-images.githubusercontent.com/6471025/216616750-12b1e200-a4f7-49b5-b785-8e68031cdfea.jpg)

**Comment by THE-SIMPLE-MARK** [comment]
> @NoahMLoomis I'm using Datarange, and if I block for instance feb 11 and feb 12, I can still select a range from feb 10 until feb 13. Imho this should not be possible, since it includes the blocked dates. ![Schermafbeelding 2023-02-03 om 14 35 58](https://user-images.githubusercontent.com/6471025/216616750-12b1e200-a4f7-49b5-b785-8e68031cdfea.jpg)

Yep, I agree. We should also be able to style how disabled dates look, for example, it would be nice if I could maybe gray out disable dates so it's more noticable on light themes. I'll reopen this issue in hopes that the issue you pointed out will be fixed and maybe my request added.

**Comment by THE-SIMPLE-MARK** [comment]
> > @NoahMLoomis I'm using Datarange, and if I block for instance feb 11 and feb 12, I can still select a range from feb 10 until feb 13. Imho this should not be possible, since it includes the blocked dates. ![Schermafbeelding 2023-02-03 om 14 35 58](https://user-images.githubusercontent.com/6471025/216616750-12b1e200-a4f7-49b5-b785-8e68031cdfea.jpg)
> 
> Yep, I couldn't agree more. I'll reopen this issue in hopes that the issue you pointed out will be fixed.

@NoahMLoomis Is there any chance that you could fix this bug? I am sadly unable to use this feature until this is fixed.

**Comment by onesine** [comment]
Don't worry about that. I will try to fix it as @NoahMLoomis is not available at the moment.

**Comment by Maxximus007** [comment]
> Don't worry about that. I will try to fix it as @NoahMLoomis is not available at the moment.

Hi, did you find the time to take a look at it?

**Comment by onesine** [comment]
Hi @Maxximus007, @THE-SIMPLE-MARK, @yoy0lol 👋

I'm sorry. Work has been keeping me very busy lately. I found some time during the day to work on it. I will publish a new version before the end of the day.

**Comment by onesine** [comment]
I have just fixed the problem. It will be published in a new version.

**Comment by THE-SIMPLE-MARK** [comment]
> I have just fixed the problem. It will be published in a new version.

Awesome, thank you for fixing this issue!
