### ISSUE TITLE
[BUG] When using asSingle and useRange='false' the incorrect month is initially shown

### ISSUE THREAD

**Issue by NoahMLoomis** [onesine/react-tailwindcss-datepicker#26]
I'm trying to show Datepickers, one to select `From`, the other to `To`. I want the default value of `To` to be a month ahead of the current date (Also the default `From` date). When I click on the `From` Datepicker, the correct date is shown along with the correct month. But when I select the `To` Datepicker, the wrong month is shown (Jan instead of Feb)

![Animation](https://user-images.githubusercontent.com/56049624/210402228-47848ad4-83e7-450a-aa26-5933565c5826.gif)

**Comment by JefteCaro** [comment]
Hi @NoahMLoomis 

Have you set the `startFrom` prop for the second picker?
