### ISSUE TITLE
Does not pass the locale parameter to the dateFormat function

### ISSUE THREAD

**Issue by dsolay** [onesine/react-tailwindcss-datepicker#270]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-tailwindcss-datepicker@1.7.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-tailwindcss-datepicker/dist/index.esm.js b/node_modules/react-tailwindcss-datepicker/dist/index.esm.js
index ca49e83..3a353a0 100644
--- a/node_modules/react-tailwindcss-datepicker/dist/index.esm.js
+++ b/node_modules/react-tailwindcss-datepicker/dist/index.esm.js
@@ -3313,7 +3313,7 @@ const Datepicker = (props) => {
                     start: value.startDate,
                     end: value.endDate
                 });
-                setInputText(`${dateFormat(value.startDate, displayFormat)}${asSingle ? "" : ` ${separator} ${dateFormat(value.endDate, displayFormat)}`}`);
+                setInputText(`${dateFormat(value.startDate, displayFormat, i18n)}${asSingle ? "" : ` ${separator} ${dateFormat(value.endDate, displayFormat, i18n)}`}`);
             }
         }
         if (value && value.startDate === null && value.endDate === null) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by onesine** [comment]
Hi @dsolay ,

Thank you for using this package and thank you for your feedback. You are indeed right. I've just released a new version ([1.7.2](https://github.com/onesine/react-tailwindcss-datepicker/releases/tag/v1.7.2)) that addresses your concern.
