### ISSUE TITLE
How to configure endDate to optional?

### ISSUE THREAD

**Issue by S-YOU** [onesine/react-tailwindcss-datepicker#36]
Currently, initial endDate can be set to null, but not later on.

**Comment by JefteCaro** [comment]
Hi @S-YOU 

`startDate` and `endDate` are both returned by default, as the component features date range.

If you just need one date, just get the `startDate` of the returned value, if there's no use for `endDate`

**Comment by S-YOU** [comment]
Thanks for the reply.

> If you just need one date, just get the startDate of the returned value, if there's no use for endDate

My usage is that endDate can be specify by user if they choose the fixed range, and also there is open date which does not have endDate. Also when editing the form, endDate can be on and off depends on the data. I can't seems to do `setValue({startDate: 'validDate', endDate: null})` too. 

![image](https://user-images.githubusercontent.com/1001175/211383832-30e1b923-3eb1-4ac7-8f23-ff62651513d2.png)

**Comment by JefteCaro** [comment]
For now, I would suggest using 2 `Datepickers` and enable `asSingle`

```js
// start date
<Datepicker
  asSingle={true}
  useRange={false}
/>
```
```js
// end date
<Datepicker
  asSingle={true}
  useRange={false}
/>

```

Use the first one for your start date and the other for your end date. So you can control which should be null

**Comment by S-YOU** [comment]
Great advice, thank you very much and quick reply!

**Comment by pulpdood** [comment]
Hi, just wondering if it's possible to implement an optional endDate for the single Datepicker with useRange={true}? I would like to use a single Datepicker component for that as there is limited horizontal space on my page. Thank you!

**Comment by DavidQuartz** [comment]
@JefteCaro 
> For now, I would suggest using 2 `Datepickers` and enable `asSingle`
> 
> ```js
> // start date
> <Datepicker
>   asSingle={true}
>   useRange={false}
> />
> ```
> 
> ```js
> // end date
> <Datepicker
>   asSingle={true}
>   useRange={false}
> />
> ```
> 
> Use the first one for your start date and the other for your end date. So you can control which should be null

WIth this approach, what will you set as the value for each component? Even though `asSingle` is set to `true`, the component seems to expect a value object containing `startDate` and `endDate`. And when you provide that value, it uses the start date.
