### ISSUE TITLE
[Bug] month label wrong display when set i18n to vi

### ISSUE THREAD

**Issue by fchienvuhoang** [onesine/react-tailwindcss-datepicker#38]
<img width="367" alt="Screenshot 2023-01-11 at 10 13 28" src="https://user-images.githubusercontent.com/4451749/211709646-d09189d6-98ff-4c31-8c93-66e37ebeaf92.png">
<img width="395" alt="Screenshot 2023-01-11 at 10 13 41" src="https://user-images.githubusercontent.com/4451749/211709654-468cbc6f-f29e-43c2-9196-40048f153010.png">

My code
<img width="464" alt="Screenshot 2023-01-11 at 10 15 49" src="https://user-images.githubusercontent.com/4451749/211709745-7e49b7fa-d187-4f04-8806-74d5ffed6325.png">

**Comment by JefteCaro** [comment]
Hi @fchienvuhoang 

Thank you for the feedback.

Unfortunately this one's a bug from the third-party plugin (`dayjs`) we use for `i18n`. (source [here](https://github.com/iamkun/dayjs/blob/dev/src/locale/vi.js))

If you can translate and send here the exact translations, maybe we can make it work.

**Comment by onesine** [comment]
Hello @fchienvuhoang 👋
Thank you for using our package.

So sorry for the delay. Thanks for the feedback. But it seems that this has already been taken care of in the new version. So we can close this issue.

PRs are always welcome 🎉.
