### ISSUE TITLE
onChange does not fire when using the shortcuts

### ISSUE THREAD

**Issue by eduardlleshi** [onesine/react-tailwindcss-datepicker#4]
I've noticed that when using the shortcuts will not trigger the onChange function. The input does get updated with the range from the shortcuts, but the function does not fire.

It works fine if I select a range from the calendar manually.

I'm not sure if I missed something from the docs (I can replicate it with code from the [demo page](https://react-tailwindcss-datepicker.vercel.app/demo)), or if this is a bug.

**Comment by onesine** [comment]
Hi 👋 @eduardlleshi
Thank you very much for reporting this problem.

I'm really sorry for the delay. I'm new to open source contribution with a few packages to maintain right now. I am making an effort to respond as quickly as possible.

I will fix these issues very quickly.

**Comment by onesine** [comment]
@eduardlleshi i have already solved the problem.
