### ISSUE TITLE
Uncaught (in promise) ReferenceError: require is not defined 

### ISSUE THREAD

**Issue by davohambardzumyan** [onesine/react-tailwindcss-datepicker#45]
Getting issue in console on production(npm run build). 
![image](https://user-images.githubusercontent.com/25978306/212852706-0c65bbb1-93ca-4058-9154-af2a45b29fdc.png)

**Comment by srini-leanfolks** [comment]
I got this also. I think it is due to dayjs in production build uses require(cjs) instead of import(mjs)

**Comment by srini-leanfolks** [comment]
I used requirejs package also via cdn. But i got other issues.
![image](https://user-images.githubusercontent.com/94096449/213372201-e9b42e2f-6862-48fc-8a82-645a41ce2484.png)

**Comment by davohambardzumyan** [comment]
@srini-leanfolks I moved the package out of node modules and fixed this part for myself.

in index.esm.js you can replace require to `import isBetween from 'dayjs/plugin/isBetween` (on line 940)

and i commented switch case (on line 150) 

Waiting for when will be fixed this part. :)

**Comment by haithem-rihane** [comment]
@srini-leanfolks how it gets updated in npmjs.com ?

**Comment by srini-leanfolks** [comment]
> @srini-leanfolks how it gets updated in npmjs.com ?

Sorry I didn't get you

**Comment by JefteCaro** [comment]
Fix in [`v1.4.1`](https://github.com/onesine/react-tailwindcss-datepicker/releases/tag/v1.4.1)

Closing this issue

**Comment by gelmio** [comment]
I'm still getting the same error in production builds. Using version 1.4.1. (dayjs v1.11.6)
