### ISSUE TITLE
Feature request: ability to customize button icons

### ISSUE THREAD

**Issue by lionstigersandbears** [onesine/react-tailwindcss-datepicker#49]
Love the datepicker, but my designer wants to use a specific icon for the calendar button. I can *almost* work around it using CSS (see code) but then I lose the close button as they both have the same selector and so they both look the same, breaking the component visually. 

`
.custom-datepicker button.absolute.right-0 {
  svg {  
    opacity: 0;  
  }  
  &:after {  
    content: ' ';  
    background-size: contain;  
    display: block;  
    width: 32px;  
    height: 32px;  
    background-image: url("data:image/svg+xml...");  
    ...  
  }  
}  
`

Ideally, it could work something like this: 

`
<Datepicker 
  value={dateFilter}
  onChange={setDateFilter} 
  calendarIcon={<MySVGIcon className="w-5 h-5" />}
/>
`

Cheers!

**Comment by onesine** [comment]
Hi @lionstigersandbears 👋
Thank you for using our package.

It seems that this is already supported in version 1.4.2 🎉. So we can close this issue. 
Thanks to @JefteCaro for adding this option.

PRs are always welcome 🎉.
