### ISSUE TITLE
How do I disable dark mode?

### ISSUE THREAD

**Issue by rahul4200** [onesine/react-tailwindcss-datepicker#54]
How do I disable dark mode. The moment I set my Windows 11 to dark mode, the datepicker changed to darkmode. My site is fully white and I don't want this to change to dark mode. I want it to always stay in light mode. I was unable to find a prop to do that. Kindly suggest.

**Comment by kudaleganesh** [comment]
Same here. By default, it is set to dark mode.

**Comment by onesine** [comment]
Hi @rahul4200  and @kudaleganesh 👋

Thanks for your feedback.

Ideally, this component should not need any special props to disable or enable the dark mode. By default, it uses the system settings to determine the mode. But you can specify in your `tailwind.config.js` configuration file that you want to handle the mode change manually.

In your `tailwindcss.config.js` file
```
module.exports = {
  darkMode: 'class',
  // ...
}
```
This code should allow you to solve the problem. For more information on the dark mode, you can consult

**Comment by onesine** [comment]
@rahul4200 & @kudaleganesh I think we can close this issue. If you have any issues, you can reopen it so we can discuss it.
