### ISSUE TITLE
Feature Request: Popover Direction

### ISSUE THREAD

**Issue by devinmatte** [onesine/react-tailwindcss-datepicker#59]
Right now it appears that the popover picks to go above or below the input depending on how much space is left, however in some cases it seems to pick wrong and gets covered up by the UI. 
I would love if there was a prop to lock the popover to either `above` or `below`, where it defaults to the current behavior when unset

**Comment by onesine** [comment]
Hi @devinmatte  👋
Thank you for using our package.

You again 😅.
Again, sorry for the delay. Thanks for the feature request. It would be really nice to have this option available. So we will implement it as soon as possible.

PRs are always welcome 🎉.
