### ISSUE TITLE
Add a new prop to change the format date

### ISSUE THREAD

**Issue by phithu** [onesine/react-tailwindcss-datepicker#6]
Hello, Thank you for creating a great component
I'm using this component, I faced the issue can not change the format date (example I want to change to "DD-MM-YYYY")
I checked your code on the Datepicker.tsx file will call formatDate function, but you don't pass the format param to this function

**Comment by onesine** [comment]
Hi 👋 @phithu 
Thanks for the remark and especially for using the component. You are right, I don't send the format parameters to the function. I should be able to add the functionality you are asking for very soon.

**Comment by yestoall** [comment]
i'm waiting for this change too... good work onesine :)

**Comment by onesine** [comment]
Hi @yestoall  👋
Thank you for your feedback. It makes me very happy. 

I would also like to apologize for the time it takes for some requests to be processed.

@yestoall and @phithu 
It will come very soon with new features.

**Comment by yestoall** [comment]
i can't wait to see your new features :)

thanks from spain

**Comment by NoahMLoomis** [comment]
This is addressed in PR #19

**Comment by onesine** [comment]
Thanks to @NoahMLoomis for this PR.

We are working as fast as we can to release it for you to enjoy. 

More great features will be coming very soon.
