### ISSUE TITLE
[Feature request] Daterange minimum days

### ISSUE THREAD

**Issue by Maxximus007** [onesine/react-tailwindcss-datepicker#7]
Your calendar looks really good! Would like to use it in a little project of mine. 
Hope the Disable dates feature is coming soon ;) 
Perhaps you can implement the following feature as well: Minimum days to select.

Thanks!

**Comment by onesine** [comment]
Hi 👋 @Maxximus007 .
I'm glad you find it good and want to use it on your project.
Thanks for the request. I will take note of it. The feature you ask for will surely come in the next versions very soon.

**Comment by onesine** [comment]
I think this feature is already available in the new versions. So we can close this issue. Feel free to reopen another one if you have other proposals. Thanks for this feature request @Maxximus007 and sorry for the delay.

PRs are always welcome 🎉.

**Comment by Maxximus007** [comment]
Hi, unfortunately the disabled dates is not working as expected in a range. It's still possible to select a range that includes the disabled dates. Hope you can have a look! Thank you for your efforts.
![Schermafbeelding 2023-02-03 om 14 35 58](https://user-images.githubusercontent.com/6471025/220342218-eb8b77f0-c6eb-4ae4-98c6-db404b5c1dac.jpg)
