### ISSUE TITLE
Input value doesn't reset using React Hook Form

### ISSUE THREAD

**Issue by SimonBellucci** [onesine/react-tailwindcss-datepicker#82]
Hey there,

I'm using React Hook Form in my project, and I've noticed an issue with the Datepicker. After using the `reset` function from React Hook Form, the input value does not reset to its default value, while the field value in the form is indeed null.

Here is a sandbox that reproduces the issue : https://codesandbox.io/s/priceless-babbage-zqzm5v?file=/src/App.js

You can open the RHF DevTools to see exactly how the values change.

**Comment by onesine** [comment]
Hi @SimonBellucci  👋
Thanks for your feadback.
You are right and I think this behavior is pretty normal. I would suggest that you do not control the date picker field through the React Hook form until we find a solution. You can just manually reset the field.

**Comment by SimonBellucci** [comment]
I just found a workaround by manually setting the value this way:

```
<DatePicker
    separator="/"
    inputName={name}
    value={field.value || {startDate: null, endDate: null}}
    onChange={handleValueChange}
    placeholder={placeholder}
/>
```

**Comment by onesine** [comment]
Yes, it should work. Thank you for this alternative solution.

**Comment by lekshmic-sadaindia** [comment]
@onesine the above workaround will reset the values but the style on the end date selected will continue to exist 
<img width="715" alt="Screenshot 2023-09-19 at 3 00 32 PM" src="https://github.com/onesine/react-tailwindcss-datepicker/assets/118151666/1d67528e-cbf6-4f89-81a4-3457df2e767a">

**Comment by ayberkcal** [comment]
I've have faced same issue. Is it bug? If it is bug, is there any investigation about situation?

**Comment by jaedung** [comment]
Same issue here. I need to clear the value on the datepicker.
