### ISSUE TITLE
Dark mode problem

### ISSUE THREAD

**Issue by dorukozerr** [onesine/react-tailwindcss-datepicker#88]
First of all fantastic project thank you for it. I have a problem: texts need to be in the correct color on dark mode. I tried to update them, but it also didn't work. Am I missing something?
<img width="622" alt="image" src="https://user-images.githubusercontent.com/74541855/224684077-7b4fe6db-14d0-4daf-ac55-1bb1ae2a6c9d.png">

**Comment by 684efs3** [comment]
You might need to add the tailwind colors into your tailwindconfig. Looks like maybe you are missing white?

**Comment by dorukozerr** [comment]
I have somehow overwritten the styles. The problem was solved when I disabled some CSS.
